---
default_language_version:
  python: python3.10
exclude: ^utils/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.2
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        exclude: |
          (?x)(^
            dbmodels/alembic/.*
            | dbmodels/tests/.*
            | api/tests/.*
            | api/pandora/utils.py
            | api/pandora/core/database/queries.py
          $)
        additional_dependencies:
          - "pydantic"
          - "types-attrs"
          - "types-freezegun"
          - "types-requests"
          - "sqlalchemy[mypy]"
